### ISSUE TITLE
Hipmost Private List gives NoMethodError

### ISSUE THREAD

**Issue by STSWarren** [orbitalimpact/hipmost#13]
Ruby Version:
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

Command: 
./hipmost-master/exe/hipmost -v private list

Error:
Traceback (most recent call last):
        10: from ./hipmost-master/exe/hipmost:48:in `<main>'
         9: from /home/sa/work/hipmost-master/lib/hipmost.rb:16:in `run'
         8: from /home/sa/work/hipmost-master/lib/hipmost/cmds/private.rb:19:in `run'
         7: from /home/sa/work/hipmost-master/lib/hipmost/cmds/private.rb:24:in `list'
         6: from /home/sa/work/hipmost-master/lib/hipmost/hipchat.rb:21:in `direct_channels'
         5: from /home/sa/work/hipmost-master/lib/hipmost/hipchat.rb:21:in `flat_map'
         4: from /home/sa/work/hipmost-master/lib/hipmost/hipchat.rb:21:in `each'
         3: from /home/sa/work/hipmost-master/lib/hipmost/hipchat.rb:23:in `block in direct_channels'
         2: from /home/sa/work/hipmost-master/lib/hipmost/hipchat.rb:23:in `map'
         1: from /home/sa/work/hipmost-master/lib/hipmost/hipchat.rb:23:in `each'
/home/sa/work/hipmost-master/lib/hipmost/hipchat.rb:30:in `block (2 levels) in direct_channels': undefined method `[]' for nil:NilClass (NoMethodError)

Comment:
When I run the command "./hipmost-master/exe/hipmost -v public list" or "./hipmost-master/exe/hipmost -v public import "HipchatRoom" "Channel":"MattermostRoom"" it works fine and executes without problem. I have been trying to fix it myself but so far to no avail. Any help would be appreciated.

**Comment by ylluminate** [comment]
Resolved in v2 rewrite. The old gem architecture (lib/, exe/, spec/) has been replaced with a standalone single-file script. See the updated README for the new workflow.
