### ISSUE TITLE
Syntax error in mattermost.rb:2

### ISSUE THREAD

**Issue by Alwaysc0d3** [orbitalimpact/hipmost#14]
Getting an syntax error: 

```
bash-4.2# hipmost users -p ./data -v
/usr/local/share/gems/gems/hipmost-1.0/lib/hipmost/mattermost.rb:2:in `require_relative': /usr/local/share/gems/gems/hipmost-1.0/lib/hipmost/mattermost/channel.rb:4: syntax error, unexpected ',' (SyntaxError)
      def self.from_hipchat(room, name:, team: )
                                        ^
/usr/local/share/gems/gems/hipmost-1.0/lib/hipmost/mattermost/channel.rb:12: syntax error, unexpected ','
      def initialize(name:, team:, display_name:, type:, header:)
                           ^
/usr/local/share/gems/gems/hipmost-1.0/lib/hipmost/mattermost/channel.rb:25: syntax error, unexpected keyword_end, expecting end-of-input
	from /usr/local/share/gems/gems/hipmost-1.0/lib/hipmost/mattermost.rb:2:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/hipmost-1.0/lib/hipmost.rb:4:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/hipmost-1.0/exe/hipmost:7:in `<top (required)>'
	from /usr/local/bin/hipmost:23:in `load'
	from /usr/local/bin/hipmost:23:in `<main>'
```

Using Ruby version ruby 2.0.0p648 (2015-12-16) [x86_64-linux] 
at
Centos 7.6.1810
@docker

**Comment by gabrielrios** [comment]
You need a newer Ruby version (duplicated #9)
