### ISSUE TITLE
post.rb : wrong number of arguments (given 2, expected 3) (ArgumentError)

### ISSUE THREAD

**Issue by EdHarkin** [orbitalimpact/hipmost#8]
Hi, I'm receiving this error when I try convert a room:

/usr/local/lib/ruby/gems/2.5.0/gems/hipmost-1.0/lib/hipmost/hipchat/post.rb:8:in `initialize': wrong number of arguments (given 2, expected 3) (ArgumentError)''

Any suggestions?

Thank you

**Comment by ylluminarious** [comment]
@EdHarkin Sorry for the delay. Would you mind posting more output from the error? I think you're just posting the last line.

**Comment by EdHarkin** [comment]
Thanks for replying @ylluminarious. Here is the full output:

`me@iMac~ $ hipmost -v rooms import “Room” “team”:”general"
Parsing rooms for Hipchat and Mattermost...
Hipchat room is:               Room
Mattermost team & channel are: team:general
Successfully parsed rooms

Opening /Users/me/Room.jsonl for writing...
Writing version header...
Writing team info...
Writing channel info...
Writing room members...
Traceback (most recent call last):
	11: from /usr/local/bin/hipmost:23:in `<main>'
	10: from /usr/local/bin/hipmost:23:in `load'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/hipmost-1.0/exe/hipmost:48:in `<top (required)>'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/hipmost-1.0/lib/hipmost.rb:14:in `run'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/hipmost-1.0/lib/hipmost/cmds/room.rb:23:in `run'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/hipmost-1.0/lib/hipmost/cmds/room.rb:47:in `import'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/hipmost-1.0/lib/hipmost/cmds/room.rb:54:in `save'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/hipmost-1.0/lib/hipmost/cmds/room.rb:54:in `open'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/hipmost-1.0/lib/hipmost/cmds/room.rb:64:in `block in save'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/hipmost-1.0/lib/hipmost/cmds/room.rb:64:in `each'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/hipmost-1.0/lib/hipmost/cmds/room.rb:65:in `block (2 levels) in save'
/usr/local/lib/ruby/gems/2.5.0/gems/hipmost-1.0/lib/hipmost/hipchat/room.rb:46:in `users': undefined method `[]' for nil:NilClass (NoMethodError)`

**Comment by ylluminarious** [comment]
@EdHarkin Hmm, it seems that you're posting two different errors. The first one that you gave is different from this most recent one. The latter is also somewhat hard to decipher because it sounds like your room doesn't have any users, which shouldn't happen as far as I remember. But it sounds like a case where some sample data would be useful. Again, it's also different from your first error so I'm not quite sure what the root(s) of your problem(s) is / are.

Also, you should probably [read up on Github's markdown formatting](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) because your comment is a little hard to read.

**Comment by bhoover19** [comment]
I am getting this error as well.

command run - hipmost public import "Fantasy Football" "Fantasy Football":"General" - path /usr/local/data 

error - /var/lib/gems/2.5.0/gems/hipmost-1.0/lib/hipmost/cmds/room.rb:62:in 'block (3 levels) in save': undefined method 'to_jsonl' for nil:NilClass (NoMethodError).  Did you mean? to_json

**Comment by developerrespig** [comment]
Actually I got the ArgumentError and I don't know how to fix it. Here is the command that I execute:

hipmost -v public import "testroom" "migration":"testroom"

The Output:
Parsing rooms for Hipchat and Mattermost...
Hipchat room is:               testroom
Mattermost team & channel are: migration:testroom
Successfully parsed rooms

Opening /home/xxx/tmp/testroom.jsonl for writing...
Writing version header...
Writing team info...
Writing channel info...
Writing room members...
Writing room posts (newest to oldest)...
On room 1
/var/lib/gems/2.3.0/gems/hipmost-1.0/lib/hipmost/hipchat/post.rb:8:in `initialize': wrong number of arguments (given 2, expected 3) (ArgumentError)
        from /var/lib/gems/2.3.0/gems/hipmost-1.0/lib/hipmost/hipchat/post_repository.rb:33:in `new'
        from /var/lib/gems/2.3.0/gems/hipmost-1.0/lib/hipmost/hipchat/post_repository.rb:33:in `block in load'
        from /var/lib/gems/2.3.0/gems/hipmost-1.0/lib/hipmost/hipchat/post_repository.rb:27:in `each'
        from /var/lib/gems/2.3.0/gems/hipmost-1.0/lib/hipmost/hipchat/post_repository.rb:27:in `load'
        from /var/lib/gems/2.3.0/gems/hipmost-1.0/lib/hipmost/cmds/room.rb:76:in `tap'
        from /var/lib/gems/2.3.0/gems/hipmost-1.0/lib/hipmost/cmds/room.rb:76:in `block (2 levels) in save'
        from /var/lib/gems/2.3.0/gems/hipmost-1.0/lib/hipmost/cmds/room.rb:70:in `each'
        from /var/lib/gems/2.3.0/gems/hipmost-1.0/lib/hipmost/cmds/room.rb:70:in `block in save'
        from /var/lib/gems/2.3.0/gems/hipmost-1.0/lib/hipmost/cmds/room.rb:50:in `open'
        from /var/lib/gems/2.3.0/gems/hipmost-1.0/lib/hipmost/cmds/room.rb:50:in `save'
        from /var/lib/gems/2.3.0/gems/hipmost-1.0/lib/hipmost/cmds/room.rb:43:in `import'
        from /var/lib/gems/2.3.0/gems/hipmost-1.0/lib/hipmost/cmds/room.rb:19:in `run'
        from /var/lib/gems/2.3.0/gems/hipmost-1.0/lib/hipmost.rb:12:in `run'
        from /var/lib/gems/2.3.0/gems/hipmost-1.0/exe/hipmost:48:in `<top (required)>'
        from /usr/local/bin/hipmost:22:in `load'
        from /usr/local/bin/hipmost:22:in `<main>'

Can anyone help me with this?

**Comment by ylluminate** [comment]
Resolved in v2 rewrite. The old gem architecture (lib/, exe/, spec/) has been replaced with a standalone single-file script. See the updated README for the new workflow.
