### ISSUE TITLE
hipmost error at runtime RH7

### ISSUE THREAD

**Issue by rakyp** [orbitalimpact/hipmost#9]
After installing the gem (gem install hipmost), or using the specific_install method the binary gives the following: 

```
hipmost
/usr/local/share/gems/gems/hipmost-1.0/lib/hipmost/mattermost.rb:2:in `require_relative': /usr/local/share/gems/gems/hipmost-1.0/lib/hipmost/mattermost/channel.rb:4: syntax error, unexpected ',' (SyntaxError)
def self.from_hipchat(room, name:, team: )
^
/usr/local/share/gems/gems/hipmost-1.0/lib/hipmost/mattermost/channel.rb:14: syntax error, unexpected ','
def initialize(name:, team:, display_name:, type:, header:)
^
/usr/local/share/gems/gems/hipmost-1.0/lib/hipmost/mattermost/channel.rb:39: syntax error, unexpected keyword_end, expecting end-of-input
from /usr/local/share/gems/gems/hipmost-1.0/lib/hipmost/mattermost.rb:2:in `<top (required)>'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/local/share/gems/gems/hipmost-1.0/lib/hipmost.rb:4:in `<top (required)>'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/local/share/gems/gems/hipmost-1.0/exe/hipmost:7:in `<top (required)>'
from /usr/local/bin/hipmost:23:in `load'
from /usr/local/bin/hipmost:23:in `<main>'
```
This happens on RH7. Any help appreciated.

**Comment by gabrielrios** [comment]
can you post the return of `ruby --version`?

**Comment by rakyp** [comment]
@gabrielrios Thanks for this. By default RH7 ships with ruby 2.0.0 (this fails). I tried it with 2.5.0, it failed with the same error. I switched to ruby 2.4.3p205 and it worked fine.
